---
Name: dashboardconfig
---

SilverStripe\Security\Member:
  extensions:
    - Sunnysideup\Dashboard\Extensions\DashboardMember

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Sunnysideup\Dashboard\Extensions\DashboardSiteConfig

# this is so generic, it can break lots of other things.
#SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
#  extensions:
#    - Sunnysideup\Dashboard\Extensions\DashboardItemEditForm
